import { describe, test, expect } from 'vitest';
import { 
  normalizeNodeLabel, 
  extractNodeIdFromReference, 
  resolveVariable, 
  interpolate,
  executeNode
} from '../services/executionEngine';
import { validateWorkflow } from '../services/workflowValidation';

// Setup mock nodes
const nodes = [
  { id: 'node-1', data: { label: 'API Call', config: {} } },
  { id: 'node_2_with_underscores', data: { label: 'AI Prompt', config: {} } },
  { id: 'node-3', data: { label: 'Notification', config: {} } },
  { id: 'node-4-duplicate', data: { label: 'API Call', config: {} } }, // Duplicate label
  { id: 'node-5', data: { label: 'Loop', config: {} } }
] as any[];

const edges = [
  { source: 'node-1', target: 'node-5', sourceHandle: 'body' },
  { source: 'node-1', target: 'node_2_with_underscores' },
  { source: 'node_2_with_underscores', target: 'node-3' }
] as any[];

describe('Reference System Tests', () => {

  test('normalizeNodeLabel', () => {
    expect(normalizeNodeLabel('API Call')).toBe('api_call');
    expect(normalizeNodeLabel('Webhook (1)')).toBe('webhook__1_');
    expect(normalizeNodeLabel('Send-Email')).toBe('send_email');
  });

  test('extractNodeIdFromReference', () => {
    // By direct node id format generated by Insert Data
    expect(extractNodeIdFromReference('node_node-1', nodes)).toBe('node-1');
    expect(extractNodeIdFromReference('node_node_2_with_underscores', nodes)).toBe('node_2_with_underscores');
    // By raw node id
    expect(extractNodeIdFromReference('node-1', nodes)).toBe('node-1');
    // By safe label
    expect(extractNodeIdFromReference('api_call', nodes)).toBe('node-1');
    expect(extractNodeIdFromReference('api_call_output', nodes)).toBe('node-1');
  });

  test('resolveVariable', () => {
    const ctx = {
      'node_node-1': { data: { rows: [1, 2, 3] }, count: 3 },
      'api_call': { data: { rows: [1, 2, 3] }, count: 3 }, // the canonical normalized mapping
      'node_node_2_with_underscores': { result: 'hello' }
    };

    const res1 = resolveVariable('node_node-1.data.rows', ctx, nodes);
    expect(res1.value).toEqual([1, 2, 3]);
    expect(res1.found).toBe(true);

    const res2 = resolveVariable('api_call.count', ctx, nodes);
    expect(res2.value).toBe(3);
    expect(res2.found).toBe(true);

    const res3 = resolveVariable('node-1.count', ctx, nodes);
    expect(res3.value).toBe(3);
    expect(res3.found).toBe(true);
  });

  test('validateWorkflow references', () => {
    // Test: Loop using Response Body (API Call -> Loop)
    const loopNode = { 
      id: 'node-5', 
      data: { 
        type: 'loop', 
        label: 'Loop',
        config: { items: '${node_node-1.data.rows}' } 
      } 
    };

    const promptNode = {
      id: 'node_2_with_underscores',
      data: {
        type: 'ai_prompt',
        label: 'AI Prompt',
        config: { prompt: 'Analyze ${node_node-1.data}' }
      }
    };

    const notifyNode = {
      id: 'node-3',
      data: {
        type: 'notification',
        label: 'Notification',
        config: { message: 'Done: ${node_node_2_with_underscores.result}' }
      }
    };

    const testNodes = [nodes[0], loopNode, promptNode, notifyNode] as any[];
    const report = validateWorkflow(testNodes, edges);
    
    // It should find no configuration errors regarding variables missing
    const refErrors = report.errors.filter(e => e.message.includes('references a node that doesn\'t exist') || e.message.includes('hasn\'t run at this point'));
    expect(refErrors.length).toBe(0);
  });

  test('REGRESSION TEST: API Call Output Contract', async () => {
    // The system must agree that API Call produces `.data`, `.status`, `.headers` (not `.output`)
    
    // Mock fetch
    const originalFetch = global.fetch;
    global.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
      return {
        ok: true,
        status: 200,
        statusText: 'OK',
        headers: new Headers({ 'content-type': 'application/json' }),
        json: async () => ({ id: 42, name: 'Test User' }),
        text: async () => JSON.stringify({ id: 42, name: 'Test User' })
      } as unknown as Response;
    };

    try {
      const apiConfig = {
        url: 'https://dummyjson.com/users/1',
        method: 'GET'
      };
      const apiCtx = {};
      const apiLog = async () => {};
      
      const apiResult = await executeNode('api_call', apiConfig, apiCtx, apiLog) as any;
      
      expect(apiResult).toBeDefined();
      expect(apiResult.status).toBe(200);
      expect(apiResult.data).toEqual({ id: 42, name: 'Test User' });
      expect(apiResult.headers).toBeDefined();
      expect(apiResult.output).toEqual({ id: 42, name: 'Test User' }); // TEST: Backwards compatibility for legacy .output!

      // Now test that interpolation resolves this correct contract for an AI Prompt
      const workflowCtx = {
        'node_node-api': apiResult // executionEngine puts the result here
      };
      
      const promptTemplate = 'Summarize this user: ${node_node-api.data.name} (ID: ${node_node-api.data.id})';
      const resolvedPrompt = interpolate(promptTemplate, workflowCtx);
      
      expect(resolvedPrompt).toBe('Summarize this user: Test User (ID: 42)');

      // TEST 6: Invalid output path - verify new specific error message
      try {
        interpolate('Test ${node_node-api.wrong_key}', workflowCtx);
        throw new Error('Interpolate should have thrown');
      } catch (err: any) {
        // Mock buildExecutionIssue with this error
        const { buildExecutionIssue } = await import('../services/executionEngine');
        const issue = buildExecutionIssue({ id: 'dummy' } as any, 'ai_prompt', err.message);
        
        expect(issue.message).toContain('The reference ${node_node-api.wrong_key} could not be resolved');
        expect(issue.reason).toContain('requested output key "wrong_key" was not found');
        expect(issue.suggestion).toContain('Check the reference. Available properties:');
      }
    } finally {
      global.fetch = originalFetch; // restore
    }
  });

});
